<template><div><div class="page-header"><div><h1 class="page-title">域名</h1><p class="page-subtitle">统一管理应用公网入口可选的域名与默认签发者</p></div><button class="btn btn-primary" @click="openCreate">+ 添加域名</button></div><div v-if="error" class="k8s-banner k8s-banner-warn section-gap">⚠ {{ error }}</div><div v-if="loaded && domains.length" class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>域名</th><th>默认 Issuer</th><th>说明</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="domain in domains" :key="domain.id"><td class="cell-primary">{{ domain.hostname }}</td><td>{{ domain.issuer_ref || '-' }}</td><td>{{ domain.description || '-' }}</td><td><span class="badge" :class="domain.enabled ? 'badge-online' : 'badge-offline'">{{ domain.enabled ? '已启用' : '已停用' }}</span></td><td><div class="btn-group"><button class="btn btn-sm" @click="openEdit(domain)">编辑</button><button class="btn btn-sm btn-danger" @click="remove(domain)">删除</button></div></td></tr></tbody></table></div></div><div v-if="showModal" class="overlay" @click.self="showModal=false"><div class="modal"><h2 class="modal-title">{{ editing ? '编辑域名' : '添加域名' }}</h2><form @submit.prevent="save"><div class="form-group"><label class="form-label">域名</label><input v-model.trim="form.hostname" class="form-input" placeholder="api.example.com" required /></div><div class="form-group"><label class="form-label">默认 Issuer</label><input v-model.trim="form.issuer_ref" class="form-input" placeholder="letsencrypt-prod" /></div><div class="form-group"><label class="form-label">说明</label><input v-model.trim="form.description" class="form-input" /></div><label class="check-row"><input v-model="form.enabled" type="checkbox" /> 启用此域名</label><div class="modal-actions"><button type="button" class="btn" @click="showModal=false">取消</button><button class="btn btn-primary">保存</button></div></form></div></div></div></template>
<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../api/index.js'
const domains=ref([]), loaded=ref(false), error=ref(''), showModal=ref(false), editing=ref(null), form=ref(empty())
function empty(){return {hostname:'',issuer_ref:'',description:'',enabled:true}}
async function fetchDomains(){try{domains.value=await api.get('/domains')||[]}catch(e){error.value=e.message||'加载域名失败'}finally{loaded.value=true}}
function openCreate(){editing.value=null;form.value=empty();showModal.value=true} function openEdit(domain){editing.value=domain;form.value={hostname:domain.hostname,issuer_ref:domain.issuer_ref||'',description:domain.description||'',enabled:domain.enabled};showModal.value=true}
async function save(){try{if(editing.value) await api.put(`/domains/${editing.value.id}`,form.value);else await api.post('/domains',form.value);showModal.value=false;await fetchDomains()}catch(e){error.value=e.message||'保存域名失败'}} async function remove(domain){try{await api.delete(`/domains/${domain.id}`);await fetchDomains()}catch(e){error.value=e.message||'删除域名失败'}} onMounted(fetchDomains)
</script><style scoped>.page-header{display:flex;justify-content:space-between;gap:var(--space-16)}.page-subtitle{margin:var(--space-4) 0;color:var(--text-secondary);font-size:13px}.check-row{display:flex;gap:8px;align-items:center;color:var(--text-secondary);font-size:13px}@media(max-width:640px){.page-header{flex-direction:column}.page-header .btn{width:100%}}</style>
