<template>
  <div class="page-shell registry-page">
    <header class="page-header">
      <div>
        <h1 class="page-title">自托管制品库</h1>
        <p class="page-subtitle">由 Cylism 在集群中部署和管理的 OCI 制品库，为平台应用提供私有镜像存储与分发能力。</p>
      </div>
      <button data-testid="deploy-registry" class="btn btn-primary" :disabled="!loaded || Boolean(registry)" @click="openCreate"><Plus :size="16" /> 部署制品库</button>
    </header>

    <p v-if="error" class="form-error" role="alert">{{ error }}</p>
    <div v-if="!loaded" class="empty-state">正在读取制品库配置...</div>
    <section v-else-if="!registry" class="registry-empty" data-testid="registry-empty">
      <Database :size="26" />
      <div><h2>尚未部署自托管制品库</h2><p>部署后，平台会创建受认证保护、使用持久化存储并通过集群入口提供服务的 OCI Registry。</p></div>
    </section>
    <template v-else>
      <section class="registry-summary" data-testid="registry-summary">
        <div><span class="metric-label">入口地址</span><strong>{{ endpointURL(registry) }}</strong><small>{{ registry.insecure_http ? 'HTTP，凭据和镜像层以明文传输' : `HTTPS，证书 ${registry.certificate_name || '未关联'}` }}</small></div>
        <div><span class="metric-label">运行状态</span><strong :class="statusClass(registry.status)">{{ statusLabel(registry.status) }}</strong><small>{{ registry.last_error || 'Registry 工作负载状态已同步' }}</small></div>
        <div><span class="metric-label">持久化存储</span><strong>{{ registry.pvc_name }}</strong><small>{{ registry.storage_class_name }} · {{ registry.storage_size }} · {{ registry.pvc_phase || '等待状态同步' }}</small></div>
        <div><span class="metric-label">节点下发</span><strong>{{ mirrorStatus(registry) }}</strong><small>选择节点后写入 K3s registries.yaml</small></div>
      </section>

      <section class="registry-details">
        <div class="section-heading"><div><h2>Registry 配置</h2><p>凭据只以加密形式保存，不会再次展示。</p></div><div class="section-actions"><button class="icon-button" title="刷新状态" aria-label="刷新状态" :disabled="refreshing" @click="load"><RefreshCw :size="17" :class="{ 'is-spinning': refreshing }" /></button><button class="btn btn-secondary" @click="openEdit">编辑</button><button class="btn btn-danger" @click="deleteOpen = true">删除</button></div></div>
        <dl class="detail-grid"><div><dt>Registry 镜像</dt><dd>{{ registry.registry_image }}</dd></div><div><dt>命名空间</dt><dd>{{ registry.namespace }}</dd></div><div><dt>数据节点</dt><dd>{{ registry.data_node }}</dd></div><div><dt>运行资源</dt><dd>CPU {{ registry.cpu_request }} - {{ registry.cpu_limit }} · 内存 {{ registry.memory_request }} - {{ registry.memory_limit }}</dd></div><div><dt>拉取账号</dt><dd>{{ registry.pull_username }}</dd></div><div><dt>TLS 证书</dt><dd>{{ registry.insecure_http ? '不使用（HTTP）' : registry.certificate_name || '未关联平台证书' }}</dd></div></dl>
      </section>

      <section class="registry-details">
        <div class="section-heading"><div><h2>节点镜像配置</h2><p>只会写入所选集群节点，并重启对应的 K3s 服务。</p></div><button class="btn btn-secondary" :disabled="selectedNodes.length === 0 || submitting" @click="applyNodes"><Send :size="16" /> 下发至 {{ selectedNodes.length }} 个节点</button></div>
        <div v-if="clusterNodes.length" class="node-options"><label v-for="server in clusterNodes" :key="server.id" class="node-option"><input v-model="selectedNodes" :value="server.id" type="checkbox" /><span><strong>{{ server.k8s_node_name || server.name }}</strong><small>{{ server.host }} · {{ server.cluster_role }}</small></span></label></div>
        <p v-else class="form-hint">尚无已绑定的 K3s 节点。</p>
      </section>
    </template>

    <Teleport to="body"><div v-if="showForm" class="overlay registry-overlay" @click.self="closeForm"><div class="modal registry-modal"><h2 class="modal-title">{{ registry ? '编辑制品库' : '部署制品库' }}</h2><form @submit.prevent="save">
      <div class="form-group"><label class="form-label">名称</label><input v-model.trim="form.name" class="form-input" required placeholder="平台制品库" /></div>
      <div class="form-row"><div class="form-group"><label class="form-label">命名空间</label><input v-model.trim="form.namespace" class="form-input" required placeholder="cylism-system" /></div><div class="form-group"><label class="form-label">Registry 镜像</label><input v-model.trim="form.registry_image" class="form-input" required placeholder="registry:2" /></div></div>
      <div class="form-group"><label class="form-label">访问地址</label><input v-model.trim="form.endpoint" class="form-input" required :disabled="Boolean(registry)" placeholder="registry.example.com:31813" /><p class="form-hint">填写解析到集群入口的独立域名，可附带端口。平台会创建对应 Host 的 Ingress，将该地址转发到 Registry；后续节点用它推送和拉取镜像，创建后不可直接修改。</p></div>
      <div class="form-row"><div class="form-group"><label class="form-label">数据节点</label><select v-model="form.data_node" class="form-select registry-data-node-select" required :disabled="Boolean(registry) || registryDataNodes.length === 0"><option value="" disabled>选择承载数据的 Kubernetes 节点</option><option v-for="node in registryDataNodes" :key="node" :value="node">{{ node }}</option></select><p class="form-hint">仅展示 Ready Kubernetes 节点。Registry 与 local-path PVC 会固定在该节点；创建后不可修改。</p></div><div class="form-group"><label class="form-label">StorageClass</label><select v-model="form.storage_class_name" class="form-select registry-storage-class-select" required :disabled="Boolean(registry)"><option v-for="storageClass in storageClasses" :key="storageClass" :value="storageClass">{{ storageClass }}</option></select><p class="form-hint">仅展示符合 WaitForFirstConsumer 要求的可用存储类。</p></div></div>
      <div class="form-group"><label class="form-label">PVC 容量</label><input v-model.trim="form.storage_size" class="form-input" required :disabled="Boolean(registry)" placeholder="100Gi" /><p class="form-hint">在命名空间内创建 <code>cylism-oci-registry-data</code>；删除制品库时 PVC 会保留。</p></div>
      <section class="resource-config"><div class="section-heading"><div><h3>运行资源</h3><p>为 Registry Pod 预留并限制 CPU 与内存用量。</p></div></div><div class="resource-grid"><label class="form-group"><span class="form-label">CPU Request</span><input v-model.trim="form.cpu_request" class="form-input" required placeholder="100m" /></label><label class="form-group"><span class="form-label">CPU Limit</span><input v-model.trim="form.cpu_limit" class="form-input" required placeholder="500m" /></label><label class="form-group"><span class="form-label">内存 Request</span><input v-model.trim="form.memory_request" class="form-input" required placeholder="256Mi" /></label><label class="form-group"><span class="form-label">内存 Limit</span><input v-model.trim="form.memory_limit" class="form-input" required placeholder="1Gi" /></label></div></section>
      <p v-if="storagePreflight && !storagePreflight.ready" class="form-error">{{ storagePreflight.message }}</p>
      <div class="form-group"><label class="form-label">传输方式</label><div class="transport-options"><label><input v-model="form.insecure_http" :value="false" type="radio" /> HTTPS</label><label><input v-model="form.insecure_http" :value="true" type="radio" /> HTTP</label></div></div>
      <div v-if="!form.insecure_http" class="form-group"><div class="volume-heading"><label class="form-label">TLS 证书</label><a class="btn btn-sm" href="#/network?tab=certificates">管理证书</a></div><select v-model="form.certificate_name" class="form-select registry-certificate-select" required :disabled="certificatesLoading || !form.endpoint"><option value="" disabled>{{ certificatesLoading ? '正在查找匹配证书...' : '选择已就绪且覆盖访问域名的证书' }}</option><option v-for="certificate in certificateOptions" :key="certificate.namespace + '/' + certificate.name" :value="certificate.name">{{ certificate.name }} · {{ certificate.domains.join(', ') }}</option></select><p class="form-hint">仅展示当前命名空间内、已就绪且覆盖访问域名的证书。证书续期会由 cert-manager 自动写入 Ingress 使用的 Secret。</p><p v-if="certificateError" class="form-error">{{ certificateError }}</p><p v-else-if="form.endpoint && !certificatesLoading && !certificateOptions.length" class="form-hint">没有匹配证书。请先在证书管理中创建覆盖该域名的证书，并使用当前命名空间。</p></div>
      <label v-else class="risk-confirm"><input v-model="form.confirm_insecure_http" type="checkbox" required /> 我确认 HTTP 会以明文传输镜像层与拉取凭据。</label>
      <div class="form-row"><div class="form-group"><label class="form-label">拉取账号</label><input v-model.trim="form.pull_username" class="form-input" required placeholder="cylism-pull" /></div><div class="form-group"><label class="form-label">{{ registry ? '新拉取密码（留空保持不变）' : '拉取密码' }}</label><input v-model="form.pull_password" class="form-input" type="password" :required="!registry" minlength="12" autocomplete="new-password" /></div></div>
      <div class="modal-actions"><button class="btn" type="button" @click="closeForm">取消</button><button class="btn btn-primary" :disabled="submitting || !storagePreflight?.ready || (!form.insecure_http && (!form.certificate_name || certificatesLoading))">{{ submitting ? '保存中...' : registry ? '保存配置' : '开始部署' }}</button></div>
    </form></div></div></Teleport>

    <Teleport to="body"><div v-if="deleteOpen" class="overlay registry-overlay" @click.self="deleteOpen = false"><div class="modal"><h2 class="modal-title">删除制品库</h2><p class="confirm-copy">会删除 Deployment、Service、Ingress 和认证 Secret，但会保留 PVC <code>{{ registry.pvc_name }}</code> 中的镜像数据。</p><div class="modal-actions"><button class="btn" @click="deleteOpen = false">取消</button><button class="btn btn-danger" :disabled="submitting" @click="deleteRegistry">确认删除</button></div></div></div></Teleport>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { Database, Plus, RefreshCw, Send } from 'lucide-vue-next'
import { api } from '../api/index.js'

const registry = ref(null); const servers = ref([]); const storagePreflight = ref(null); const certificateOptions = ref([]); const certificateError = ref(''); const certificatesLoading = ref(false); const loaded = ref(false); const refreshing = ref(false); const error = ref(''); const showForm = ref(false); const deleteOpen = ref(false); const submitting = ref(false); const selectedNodes = ref([]); const form = ref(newForm())
const clusterNodes = computed(() => servers.value.filter(server => server.cluster_role))
const registryDataNodes = computed(() => storagePreflight.value?.data_nodes || [])
const storageClasses = computed(() => storagePreflight.value?.storage_classes || ['local-path'])
function newForm() { return { name: '', namespace: 'cylism-system', endpoint: '', registry_image: 'registry:2', data_node: '', storage_class_name: 'local-path', storage_size: '100Gi', cpu_request: '100m', cpu_limit: '500m', memory_request: '256Mi', memory_limit: '1Gi', insecure_http: false, confirm_insecure_http: false, certificate_name: '', pull_username: 'cylism-pull', pull_password: '', project_ids: [] } }
function endpointURL(item) { return `${item.insecure_http ? 'http' : 'https'}://${item.endpoint}` }
function statusLabel(status) { return ({ ready: '就绪', deploying: '部署中', failed: '失败', degraded: '异常', pending: '待部署', migration_required: '需迁移' })[status] || '未知' }
function statusClass(status) { return status === 'ready' ? 'status-ready' : status === 'failed' || status === 'degraded' || status === 'migration_required' ? 'status-failed' : 'status-pending' }
function mirrorStatus(item) { return item.node_registry_mirror_id ? '可下发' : '未配置' }
async function load() { refreshing.value = true; error.value = ''; try { const [registries, items, preflight] = await Promise.all([api.get('/managed-oci-registries'), api.get('/servers'), api.get('/managed-oci-registries/storage-preflight')]); registry.value = registries[0] || null; servers.value = items || []; storagePreflight.value = preflight } catch (err) { error.value = err.message || '加载制品库失败' } finally { loaded.value = true; refreshing.value = false } }
function openCreate() { form.value = newForm(); showForm.value = true }
function openEdit() { const item = registry.value; form.value = { ...newForm(), name: item.name, namespace: item.namespace, endpoint: item.endpoint, registry_image: item.registry_image, data_node: item.data_node, storage_class_name: item.storage_class_name, storage_size: item.storage_size, cpu_request: item.cpu_request, cpu_limit: item.cpu_limit, memory_request: item.memory_request, memory_limit: item.memory_limit, insecure_http: item.insecure_http, confirm_insecure_http: item.insecure_http, certificate_name: item.certificate_name, pull_username: item.pull_username }; showForm.value = true }
function closeForm() { showForm.value = false; form.value = newForm(); certificateOptions.value = []; certificateError.value = '' }
async function loadMatchingCertificates() { certificateOptions.value = []; certificateError.value = ''; if (!showForm.value || form.value.insecure_http || !form.value.namespace || !form.value.endpoint) return; certificatesLoading.value = true; try { const params = new URLSearchParams({ namespace: form.value.namespace, endpoint: form.value.endpoint }); const options = await api.get(`/managed-oci-registries/certificates?${params}`); certificateOptions.value = options || []; if (!certificateOptions.value.some(item => item.name === form.value.certificate_name)) form.value.certificate_name = '' } catch (err) { certificateError.value = err.message || '读取匹配证书失败' } finally { certificatesLoading.value = false } }
async function save() { submitting.value = true; error.value = ''; try { const payload = { ...form.value }; if (registry.value && !payload.pull_password) delete payload.pull_password; if (registry.value) await api.put(`/managed-oci-registries/${registry.value.id}`, payload); else await api.post('/managed-oci-registries', payload); closeForm(); await load() } catch (err) { error.value = err.message || '保存制品库失败' } finally { submitting.value = false } }
async function applyNodes() { submitting.value = true; error.value = ''; try { await api.post(`/managed-oci-registries/${registry.value.id}/apply-node-access`, { server_ids: selectedNodes.value }); await load() } catch (err) { error.value = err.message || '下发节点配置失败' } finally { submitting.value = false } }
async function deleteRegistry() { submitting.value = true; error.value = ''; try { await api.delete(`/managed-oci-registries/${registry.value.id}`, { confirm: true }); deleteOpen.value = false; selectedNodes.value = []; await load() } catch (err) { error.value = err.message || '删除制品库失败' } finally { submitting.value = false } }
onMounted(load)
watch([showForm, () => form.value.insecure_http, () => form.value.namespace, () => form.value.endpoint], loadMatchingCertificates)
</script>

<style scoped>
.page-header,.section-heading { display:flex; align-items:flex-start; justify-content:space-between; gap:var(--space-16); }.page-subtitle,.section-heading p,.form-hint,.registry-empty p,.confirm-copy { margin:4px 0 0; color:var(--text-secondary); font-size:13px; }.registry-empty { display:flex; align-items:center; gap:16px; margin-top:28px; padding:24px 0; border-top:1px solid var(--border-muted); border-bottom:1px solid var(--border-muted); }.registry-empty h2,.section-heading h2 { margin:0; font-size:16px; }.registry-summary { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:1px; margin:26px 0; background:var(--border-muted); border:1px solid var(--border-muted); }.registry-summary>div { min-width:0; padding:16px; background:var(--surface); }.metric-label { display:block; margin-bottom:6px; color:var(--text-muted); font-size:11px; }.registry-summary strong,.registry-summary small { display:block; overflow-wrap:anywhere; }.registry-summary strong { font-size:14px; }.registry-summary small { margin-top:6px; color:var(--text-secondary); font-size:12px; }.status-ready { color:var(--success); }.status-failed { color:var(--danger); }.status-pending { color:var(--warning); }.registry-details { padding:20px 0; border-top:1px solid var(--border-muted); }.section-actions,.volume-heading { display:flex; align-items:center; gap:8px; }.volume-heading { justify-content:space-between; margin-bottom:8px; }.detail-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:16px; margin:18px 0 0; }.detail-grid dt { color:var(--text-muted); font-size:12px; }.detail-grid dd { margin:4px 0 0; overflow-wrap:anywhere; font-size:13px; }.node-options,.transport-options { display:flex; flex-wrap:wrap; gap:8px; margin-top:18px; }.node-option,.transport-options label { display:flex; align-items:center; gap:8px; padding:9px 10px; border:1px solid var(--border-muted); border-radius:var(--radius-control); font-size:13px; }.node-option span { display:grid; gap:2px; }.node-option small { color:var(--text-muted); font-size:11px; }.resource-config { margin:20px 0; padding:16px 0; border-top:1px solid var(--border-muted); border-bottom:1px solid var(--border-muted); }.resource-config h3 { margin:0; font-size:14px; }.resource-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; margin-top:14px; }.registry-modal { width:min(620px,calc(100vw - 32px)); }.registry-overlay { z-index:3000; }.risk-confirm { display:flex; gap:8px; margin:0 0 14px; color:var(--danger); font-size:13px; }.is-spinning { animation:spin .8s linear infinite; }@keyframes spin { to { transform:rotate(360deg); } }@media(max-width:760px){.page-header,.section-heading{flex-direction:column;align-items:stretch}.registry-summary{grid-template-columns:1fr 1fr}.registry-empty{align-items:flex-start}.detail-grid,.resource-grid{grid-template-columns:1fr}}@media(max-width:480px){.registry-summary{grid-template-columns:1fr}}
</style>
