<template>
  <section class="proxy-workspace" data-testid="registry-proxy-workspace">
    <div class="workspace-heading">
      <p>为单个上游 Registry 部署独立的拉取缓存；Proxy 生命周期不会自动修改节点镜像源。</p>
      <button class="btn btn-primary" data-testid="create-registry-proxy" @click="openProxy()">部署代理</button>
    </div>

    <p v-if="error" class="form-error" role="alert">{{ error }}</p>
    <div v-if="loading" class="empty-state">正在读取 Registry Proxy...</div>
    <div v-else-if="proxies.length" class="proxy-list">
      <SurfaceCard v-for="item in proxies" :key="item.id" as="article" padding="none" class="metric proxy-instance">
        <header class="proxy-instance-heading"><div><strong>{{ item.name }}</strong><span class="proxy-registry">{{ item.registry }}</span></div><span class="badge" :class="statusClass(item.status)">{{ proxyStatusLabel(item.status) }}</span></header>
        <dl class="proxy-properties"><div><dt>上游</dt><dd>{{ item.upstream_url || '-' }}</dd></div><div><dt>节点入口</dt><dd>{{ item.endpoint_host }}:{{ item.node_port }}</dd></div><div><dt>部署节点</dt><dd>{{ item.node_name }}</dd></div><div><dt>缓存</dt><dd>{{ item.cache_limit_gi }} Gi · {{ item.cleanup_interval_hours }} 小时</dd></div><div><dt>DNS</dt><dd>{{ item.dns_servers?.length ? item.dns_servers.join('，') : '集群 DNS' }}</dd></div><div class="proxy-connectivity" :class="diagnosticClass(item.last_diagnostic_status)"><dt>上游连通性</dt><dd><strong>{{ diagnosticStatusLabel(item.last_diagnostic_status) }}</strong><small v-if="item.last_diagnostic_error">{{ item.last_diagnostic_error }}</small></dd></div></dl>
        <p v-if="item.last_error" class="proxy-error">{{ item.last_error }}</p>
        <div class="proxy-actions"><button v-if="isLegacyDockerHubProxy(item)" class="btn btn-sm" :disabled="migratingID === item.id" :data-testid="`migrate-registry-proxy-${item.id}`" @click="migrationTarget = item">{{ migratingID === item.id ? '迁移中...' : '迁移资源命名' }}</button><button class="btn btn-sm" :disabled="diagnosingID === item.id" @click="diagnoseProxy(item)">{{ diagnosingID === item.id ? '诊断中...' : '诊断' }}</button><button class="btn btn-sm" @click="openDNS(item)">DNS</button><button class="btn btn-sm" @click="openProxy(item)">配置</button><button class="btn btn-sm btn-danger" :disabled="cleaningID === item.id" @click="cleanupProxy(item)">{{ cleaningID === item.id ? '清理中...' : '清理缓存' }}</button></div>
      </SurfaceCard>
    </div>
    <SurfaceCard v-else class="proxy-empty"><EmptyState message="尚未部署 Registry Proxy。可为 docker.io、registry.k8s.io 等需要加速的上游分别部署代理。" /></SurfaceCard>

    <Teleport to="body"><div v-if="showProxyModal" class="overlay" @click.self="closeProxy"><div class="modal proxy-modal"><h2 class="modal-title">{{ editingProxy ? '配置 Registry Proxy' : '部署 Registry Proxy' }}</h2><form @submit.prevent="deployProxy"><div class="form-row"><div class="form-group"><label class="form-label">代理名称</label><input v-model.trim="proxyForm.name" class="form-input" required placeholder="Kubernetes Registry 代理" /></div><div class="form-group"><label class="form-label">Registry</label><input v-model.trim="proxyForm.registry" class="form-input" required placeholder="registry.k8s.io" /></div></div><div class="form-group"><label class="form-label">上游地址</label><input v-model.trim="proxyForm.upstream_url" type="url" class="form-input" placeholder="留空时使用 Registry 对应的 HTTPS 地址" /><p class="form-hint">Docker Hub 留空会使用 registry-1.docker.io；其他 Registry 使用自身 HTTPS 地址。</p></div><div class="form-group"><label class="form-label">部署节点</label><SelectMenu v-model="proxyForm.node_name" class="form-select" required><option value="" disabled>选择可访问上游 Registry 的节点</option><option v-for="server in clusterServers" :key="server.id" :value="server.k8s_node_name">{{ server.name }} · {{ server.k8s_node_name }}</option></SelectMenu></div><div class="form-group"><label class="form-label">节点可访问 IP</label><input v-model.trim="proxyForm.endpoint_host" class="form-input" required placeholder="100.81.x.x 或 10.x.x.x" /><p class="form-hint">该地址可显式填写到同一 Registry 的节点镜像源规则。</p></div><div class="form-row"><div class="form-group"><label class="form-label">NodePort</label><input v-model.number="proxyForm.node_port" type="number" min="30000" max="32767" class="form-input" required /></div><div class="form-group"><label class="form-label">临时缓存上限 (Gi)</label><input v-model.number="proxyForm.cache_limit_gi" type="number" min="1" max="100" class="form-input" required /></div></div><div class="form-group"><label class="form-label">定期清理 (小时)</label><input v-model.number="proxyForm.cleanup_interval_hours" type="number" min="1" max="168" class="form-input" required /></div><div class="config-section-title">可选出网代理</div><div class="form-group"><label class="form-label">HTTP_PROXY</label><input v-model.trim="proxyForm.http_proxy" type="url" class="form-input" placeholder="留空保持现有配置" /></div><div class="form-group"><label class="form-label">HTTPS_PROXY</label><input v-model.trim="proxyForm.https_proxy" type="url" class="form-input" placeholder="留空保持现有配置" /></div><div class="form-group"><label class="form-label">NO_PROXY</label><input v-model.trim="proxyForm.no_proxy" class="form-input" placeholder="localhost,127.0.0.1,.cluster.local" /></div><p class="form-hint">代理地址加密保存，重新打开配置不会展示已有地址。保存后会滚动重建该 Proxy。</p><div class="modal-actions"><button type="button" class="btn" @click="closeProxy">取消</button><button class="btn btn-primary" :disabled="deploying">{{ deploying ? '提交中...' : editingProxy ? '保存配置' : '部署代理' }}</button></div></form></div></div></Teleport>
    <div v-if="migrationTarget" class="overlay" @click.self="migrationTarget = null"><div class="modal"><h2 class="modal-title">迁移代理资源命名</h2><p class="confirm-copy">将删除旧的 Deployment 和 Service，并以新资源名重建。代理会短暂中断，但入口地址和 NodePort 保持不变。</p><div class="modal-actions"><button class="btn" :disabled="migratingID === migrationTarget.id" @click="migrationTarget = null">取消</button><button class="btn btn-danger" data-testid="confirm-registry-proxy-migration" :disabled="migratingID === migrationTarget.id" @click="migrateProxy">{{ migratingID === migrationTarget.id ? '迁移中...' : '确认迁移' }}</button></div></div></div>
    <div v-if="dnsTarget" class="overlay" @click.self="closeDNS"><div class="modal"><h2 class="modal-title">配置 Proxy Pod DNS</h2><p class="confirm-copy">填写后，该 Proxy Pod 仅使用指定 DNS，不再经过 CoreDNS。留空并保存可恢复集群 DNS。</p><div class="form-group"><label class="form-label">DNS 服务器</label><input v-model.trim="dnsServersText" class="form-input" placeholder="例如 10.0.0.2,10.0.0.3" /><p class="form-hint">最多 3 个 IP，不能使用宿主机本地地址 127.0.0.53。保存后将滚动重建 Proxy Pod。</p></div><div class="modal-actions"><button class="btn" :disabled="dnsSaving" @click="closeDNS">取消</button><button class="btn btn-primary" :disabled="dnsSaving" @click="saveDNS">{{ dnsSaving ? '保存中...' : '保存 DNS' }}</button></div></div></div>
  </section>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { getRegistryProxies, createRegistryProxy, updateRegistryProxy, diagnoseRegistryProxy, cleanupRegistryProxy, migrateRegistryProxy } from '../../api/registry-proxies.js'
import { getServers } from '../../api/servers.js'
import { useAsyncResource } from '../../composables/useAsyncResource.js'
import EmptyState from '../../components/EmptyState.vue'
import SurfaceCard from '../../components/SurfaceCard.vue'

const proxies = ref([]); const servers = ref([]); const error = ref(''); const loading = ref(true); const showProxyModal = ref(false); const editingProxy = ref(null); const proxyForm = ref(blank()); const deploying = ref(false); const cleaningID = ref(null); const diagnosingID = ref(null); const migrationTarget = ref(null); const migratingID = ref(null); const dnsTarget = ref(null); const dnsServersText = ref(''); const dnsSaving = ref(false)
const proxyResource = useAsyncResource(({ signal }) => getRegistryProxies({ signal }), [])
const serverResource = useAsyncResource(({ signal }) => getServers({ signal }), [])
const clusterServers = computed(() => servers.value.filter(server => server.cluster_role))
function blank() { return { name: '', registry: 'docker.io', upstream_url: '', node_name: '', endpoint_host: '', node_port: 30500, cache_limit_gi: 10, cleanup_interval_hours: 24, dns_servers: [], http_proxy: '', https_proxy: '', no_proxy: '', clear_outbound_proxy: false } }
function proxyStatusLabel(status) { return ({ ready: '就绪', deploying: '部署中', failed: '失败', missing: '缺失' })[status] || '未知' }
function statusClass(status) { return status === 'ready' ? 'badge-online' : status === 'failed' ? 'badge-danger' : 'badge-offline' }
function diagnosticStatusLabel(status) { return ({ healthy: '出网正常', proxy_not_ready: '代理未就绪', dns_resolution_failed: 'DNS 解析失败', upstream_connect_timeout: '上游连接超时', upstream_tls_failed: 'TLS 失败', upstream_http_error: '上游响应异常', command_missing: '缺少诊断工具', diagnostic_failed: '诊断失败' })[status] || '尚未诊断' }
function diagnosticClass(status) { return status === 'healthy' ? 'is-healthy' : status ? 'is-unhealthy' : '' }
function isLegacyDockerHubProxy(item) { return item.registry === 'docker.io' && item.resource_name === 'cylism-registry-proxy' }
async function load() { loading.value = true; error.value = ''; const [proxyResult, serverResult] = await Promise.all([proxyResource.refresh(), serverResource.refresh()]); if (proxyResult !== undefined) proxies.value = proxyResult || []; else error.value = proxyResource.error.value?.message || '加载 Registry Proxy 失败'; if (serverResult !== undefined) servers.value = serverResult || []; else error.value ||= serverResource.error.value?.message || '加载集群节点失败'; loading.value = false }
function proxyPayload(item, dnsServers = item.dns_servers) { return { name: item.name, registry: item.registry, upstream_url: item.upstream_url, node_name: item.node_name, endpoint_host: item.endpoint_host, node_port: item.node_port, cache_limit_gi: item.cache_limit_gi, cleanup_interval_hours: item.cleanup_interval_hours, dns_servers: dnsServers || [], http_proxy: item.http_proxy || '', https_proxy: item.https_proxy || '', no_proxy: item.no_proxy || '', clear_outbound_proxy: Boolean(item.clear_outbound_proxy) } }
function openProxy(item = null) { editingProxy.value = item; proxyForm.value = item ? { ...blank(), name: item.name, registry: item.registry, upstream_url: item.upstream_url, node_name: item.node_name, endpoint_host: item.endpoint_host, node_port: item.node_port, cache_limit_gi: item.cache_limit_gi, cleanup_interval_hours: item.cleanup_interval_hours, dns_servers: [...(item.dns_servers || [])], no_proxy: item.no_proxy || '' } : blank(); showProxyModal.value = true }
function closeProxy() { showProxyModal.value = false; editingProxy.value = null; proxyForm.value = blank() }
async function deployProxy() { deploying.value = true; error.value = ''; try { if (editingProxy.value) await updateRegistryProxy(editingProxy.value.id, proxyPayload(proxyForm.value)); else await createRegistryProxy(proxyPayload(proxyForm.value)); closeProxy(); await load() } catch (err) { error.value = err.message || '保存 Registry Proxy 失败' } finally { deploying.value = false } }
function openDNS(item) { dnsTarget.value = item; dnsServersText.value = (item.dns_servers || []).join(',') }
function closeDNS() { if (!dnsSaving.value) { dnsTarget.value = null; dnsServersText.value = '' } }
async function saveDNS() { if (!dnsTarget.value) return; dnsSaving.value = true; error.value = ''; const item = dnsTarget.value; try { await updateRegistryProxy(item.id, proxyPayload(item, dnsServersText.value.split(',').map(value => value.trim()).filter(Boolean))); closeDNS(); await load() } catch (err) { error.value = err.message || '保存 Proxy Pod DNS 失败' } finally { dnsSaving.value = false } }
async function cleanupProxy(item) { cleaningID.value = item.id; error.value = ''; try { await cleanupRegistryProxy(item.id); await load() } catch (err) { error.value = err.message || '清理代理缓存失败' } finally { cleaningID.value = null } }
async function diagnoseProxy(item) { diagnosingID.value = item.id; error.value = ''; try { await diagnoseRegistryProxy(item.id); await load() } catch (err) { error.value = err.message || '代理出网诊断失败' } finally { diagnosingID.value = null } }
async function migrateProxy() { if (!migrationTarget.value) return; const item = migrationTarget.value; migratingID.value = item.id; error.value = ''; try { await migrateRegistryProxy(item.id); migrationTarget.value = null; await load() } catch (err) { error.value = err.message || '迁移代理资源命名失败' } finally { migratingID.value = null } }
onMounted(load)
</script>

<style scoped>
.proxy-workspace { padding-top: var(--space-20); }.workspace-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--space-16); padding-bottom: var(--space-16); border-bottom: 1px solid var(--border-muted); }.workspace-heading p, .form-hint, .confirm-copy { margin: 4px 0 0; color: var(--text-secondary); font-size: 13px; line-height: 1.5; }.proxy-list { display: grid; gap: var(--space-12); margin-top: var(--space-16); }.proxy-instance { min-height: 0; padding: 0; overflow: hidden; }.proxy-instance-heading { display: flex; align-items: center; justify-content: space-between; gap: var(--space-12); min-height: 54px; padding: 12px 16px; border-bottom: 1px solid var(--border-muted); }.proxy-instance-heading > div { display: flex; align-items: baseline; min-width: 0; gap: 10px; }.proxy-instance-heading strong { overflow-wrap: anywhere; }.proxy-registry { color: var(--text-secondary); font-family: var(--font-mono); font-size: 12px; }.proxy-properties { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); margin: 0; }.proxy-properties > div { min-width: 0; padding: 12px 16px; border-right: 1px solid var(--border-muted); border-bottom: 1px solid var(--border-muted); }.proxy-properties > div:nth-child(3n) { border-right: 0; }.proxy-properties dt { color: var(--text-muted); font-size: 10px; font-weight: 700; }.proxy-properties dd { margin: 5px 0 0; color: var(--text-secondary); font-size: 12px; overflow-wrap: anywhere; }.proxy-connectivity dd { display: grid; gap: 3px; }.proxy-connectivity strong { color: var(--text-secondary); font-size: 12px; }.proxy-connectivity small { color: var(--text-muted); font-size: 11px; line-height: 1.4; }.proxy-connectivity.is-healthy strong { color: var(--success); }.proxy-connectivity.is-unhealthy strong, .proxy-connectivity.is-unhealthy small, .proxy-error { color: var(--danger); }.proxy-error { margin: 12px 16px 0; font-size: 12px; overflow-wrap: anywhere; }.proxy-actions { display: flex; flex-wrap: wrap; gap: 8px; padding: 12px 16px; }.proxy-empty { margin-top: var(--space-16); }.proxy-modal { width: min(520px, calc(100vw - 32px)); }.config-section-title { margin: 20px 0 12px; padding-top: 16px; border-top: 1px solid var(--border-muted); font-size: 14px; font-weight: 650; }
@media (max-width: 760px) { .workspace-heading { flex-direction: column; align-items: stretch; }.workspace-heading .btn { width: 100%; }.proxy-properties { grid-template-columns: repeat(2, minmax(0, 1fr)); }.proxy-properties > div:nth-child(3n) { border-right: 1px solid var(--border-muted); }.proxy-properties > div:nth-child(2n) { border-right: 0; } }
@media (max-width: 480px) { .proxy-properties { grid-template-columns: 1fr; }.proxy-properties > div, .proxy-properties > div:nth-child(3n) { border-right: 0; }.proxy-instance-heading { align-items: flex-start; flex-direction: column; } }
</style>
