package api

import (
	clusterapi "github.com/cylism/cylism-manager/internal/api/infrastructure/cluster"
	kubernetesapi "github.com/cylism/cylism-manager/internal/api/infrastructure/kubernetes"
	networkapi "github.com/cylism/cylism-manager/internal/api/infrastructure/network"
	storageapi "github.com/cylism/cylism-manager/internal/api/infrastructure/storage"
	systemapi "github.com/cylism/cylism-manager/internal/api/system"
	"github.com/gin-gonic/gin"
)

func registerInfrastructureRoutes(apiGroup *gin.RouterGroup, server *clusterapi.ServerHandler, networkDiag *clusterapi.ServerNetworkDiagnosticsHandler, terminal *clusterapi.ServerTerminalHandler, site *networkapi.SiteHandler, operations *systemapi.OperationHandler, domain *networkapi.DomainHandler, node *clusterapi.NodeHandler, join *clusterapi.NodeJoinProgressHandler, ingress *networkapi.IngressHandler, cert *networkapi.CertHandler, k8sHandler *kubernetesapi.K8sHandler, platform *kubernetesapi.ClusterPlatformHandler, storage *storageapi.StorageHandler, network *networkapi.NetworkHandler, crd *kubernetesapi.CRDHandler, audit *systemapi.AuditHandler, dbAdmin *systemapi.DBAdminHandler) {
	servers := apiGroup.Group("/servers")
	servers.POST("", server.Create)
	servers.GET("", server.List)
	servers.GET("/resource-stats", server.ResourceStats)
	servers.GET("/network-diagnostics", networkDiag.NetworkDiagnostics)
	servers.GET("/:id", server.Get)
	servers.PUT("/:id", server.Update)
	servers.DELETE("/:id", server.Delete)
	servers.POST("/:id/unbind", server.Unbind)
	servers.POST("/:id/probe", server.Probe)
	servers.POST("/:id/precheck", server.Precheck)
	servers.GET("/:id/stats", server.Stats)
	servers.GET("/:id/terminal", terminal.Terminal)

	sites := apiGroup.Group("/sites")
	sites.POST("", site.Create)
	sites.GET("", site.List)
	sites.GET("/:id", site.Get)
	sites.PUT("/:id", site.Update)
	sites.DELETE("/:id", site.Delete)
	apiGroup.GET("/operations", operations.ListOperations)

	domains := apiGroup.Group("/domains")
	domains.GET("", domain.List)
	domains.POST("", domain.Create)
	domains.GET("/importable-certificates", domain.ListImportableCertificates)
	domains.POST("/import", domain.ImportCertificate)
	domains.GET("/claimable", domain.ListClaimable)
	domains.POST("/:id/claim", domain.Claim)
	domains.PUT("/:id", domain.Update)
	domains.POST("/:id/certificate", domain.RetryCertificate)
	domains.GET("/:id/operations", domain.ListOperations)
	domains.DELETE("/:id", domain.Delete)

	nodes := apiGroup.Group("/nodes")
	nodes.GET("", node.ListNode)
	nodes.GET("/:id/labels", node.GetLabels)
	nodes.PATCH("/:id/labels", node.UpdateLabels)
	nodes.GET("/:id/join-progress", join.JoinProgress)
	nodes.GET("/:id/drain-plan", node.DrainPlan)
	nodes.GET("/:id/removal-check", node.RemovalCheck)
	nodes.POST("/:id/preimport", node.PreImport)
	nodes.POST("/:id/import", node.ConfirmImport)
	nodes.POST("/:id/add", node.AddNode)
	nodes.POST("/:id/drain", node.DrainNode)
	nodes.POST("/:id/force-drain", node.ForceDrainNode)
	nodes.POST("/:id/rejoin", node.RejoinNode)
	nodes.DELETE("/:id", node.RemoveNode)

	routes := apiGroup.Group("/routes")
	routes.GET("", ingress.ListRoutes)
	routes.POST("", ingress.CreateRoute)
	routes.PUT("/:namespace/:name", ingress.UpdateRoute)
	routes.DELETE("/:namespace/:name", ingress.DeleteRoute)
	routes.GET("/middlewares", ingress.ListMiddlewares)
	routes.GET("/tls-stores", ingress.ListTLSStores)

	certs := apiGroup.Group("/certs")
	certs.GET("/status", cert.Status)
	certs.POST("/install", cert.Install)
	certs.GET("", cert.ListCerts)
	certs.GET("/issuers", cert.ListIssuers)
	certs.POST("/issuers", cert.CreateIssuer)
	certs.PUT("/issuers/:kind/:namespace/:name", cert.UpdateIssuer)
	certs.DELETE("/issuers/:kind/:namespace/:name", cert.DeleteIssuer)
	certs.GET("/dns-credentials", cert.ListDNSCredentials)
	certs.POST("/dns-credentials", cert.CreateDNSCredential)
	certs.PUT("/dns-credentials/:id", cert.UpdateDNSCredential)
	certs.DELETE("/dns-credentials/:id", cert.DeleteDNSCredential)
	certs.GET("/dns-providers", cert.ListDNSProviders)
	certs.GET("/dns-providers/:provider/status", cert.DNSProviderStatus)
	certs.POST("/dns-providers/:provider/install", cert.InstallDNSProvider)
	certs.POST("", cert.CreateCert)
	certs.GET("/:namespace/:name/operations", cert.ListOperations)
	certs.DELETE("/:namespace/:name", cert.DeleteCert)

	registerK8sRoutes(apiGroup, k8sHandler, platform, storage, network)
	apiGroup.GET("/system/crds", crd.CheckCRDs)
	apiGroup.GET("/audit-logs", audit.List)

	admin := apiGroup.Group("/admin/tables")
	admin.GET("", dbAdmin.ListTables)
	admin.GET("/:table", dbAdmin.ListRecords)
	admin.POST("/:table", dbAdmin.CreateRecord)
	admin.PUT("/:table/:id", dbAdmin.UpdateRecord)
	admin.DELETE("/:table/:id", dbAdmin.DeleteRecord)
}

func registerK8sRoutes(apiGroup *gin.RouterGroup, h *kubernetesapi.K8sHandler, platform *kubernetesapi.ClusterPlatformHandler, storage *storageapi.StorageHandler, network *networkapi.NetworkHandler) {
	g := apiGroup.Group("/k8s")
	g.GET("/platform", platform.Get)
	g.GET("/dashboard", h.Dashboard)
	g.GET("/namespaces", h.ListNamespaces)
	g.GET("/namespace-names", h.ListNamespaceNames)
	g.POST("/namespaces", h.CreateNamespace)
	g.PATCH("/namespaces/:name", h.UpdateNamespace)
	g.DELETE("/namespaces/:name", h.DeleteNamespace)
	g.GET("/pods", h.ListPods)
	g.GET("/pods/:namespace/:name/terminal", h.PodTerminal)
	g.GET("/deployments", h.ListDeployments)
	g.GET("/deployments/:namespace/:name", h.GetDeployment)
	g.GET("/deployments/:namespace/:name/pods", h.ListDeploymentPods)
	g.GET("/deployments/:namespace/:name/revisions", h.ListDeploymentRevisions)
	g.PATCH("/deployments/:namespace/:name/scale", h.ScaleDeployment)
	g.PATCH("/deployments/:namespace/:name/image", h.UpdateDeploymentImage)
	g.POST("/deployments/:namespace/:name/rollback", h.RollbackDeployment)
	g.GET("/statefulsets", h.ListStatefulSets)
	g.GET("/statefulsets/:namespace/:name", h.GetStatefulSet)
	g.PATCH("/statefulsets/:namespace/:name/scale", h.ScaleStatefulSet)
	g.GET("/daemonsets", h.ListDaemonSets)
	g.GET("/daemonsets/:namespace/:name", h.GetDaemonSet)
	g.GET("/services", h.ListServicesV2)
	g.GET("/services/:namespace/:name", h.GetService)
	g.GET("/services/:namespace/:name/endpoints", h.GetServiceEndpoints)
	g.PUT("/services/:namespace/:name", h.UpdateService)
	g.DELETE("/services/:namespace/:name", h.DeleteService)
	g.GET("/configmaps", h.ListConfigMaps)
	g.POST("/configmaps", h.CreateConfigMap)
	g.GET("/configmaps/:namespace/:name", h.GetConfigMap)
	g.PUT("/configmaps/:namespace/:name", h.UpdateConfigMap)
	g.DELETE("/configmaps/:namespace/:name", h.DeleteConfigMap)
	g.GET("/secrets", h.ListSecrets)
	g.POST("/secrets", h.CreateOpaqueSecret)
	g.GET("/secrets/:namespace/:name", h.GetSecret)
	g.PUT("/secrets/:namespace/:name", h.UpdateOpaqueSecret)
	g.DELETE("/secrets/:namespace/:name", h.DeleteOpaqueSecret)
	g.GET("/storage-classes", storage.ListStorageClasses)
	g.GET("/persistent-volume-claims", storage.ListPersistentVolumeClaims)
	g.GET("/persistent-volume-claims/usage", storage.ListPersistentVolumeClaimUsage)
	g.POST("/persistent-volume-claims", storage.CreatePersistentVolumeClaim)
	g.GET("/persistent-volume-migrations", storage.ListPersistentVolumeMigrations)
	g.GET("/persistent-volume-migrations/:id", storage.GetPersistentVolumeMigration)
	g.POST("/persistent-volume-migrations/:id/cleanup", storage.CleanupPersistentVolumeMigration)
	g.POST("/persistent-volume-claims/:name/migrations", storage.CreatePersistentVolumeMigration)
	g.GET("/persistent-volume-claims/:name/backups", storage.ListPersistentVolumeBackups)
	g.POST("/persistent-volume-claims/:name/backups", storage.CreatePersistentVolumeBackup)
	g.POST("/persistent-volume-claims/:name/backups/:backupID/restore", storage.RestorePersistentVolumeBackup)
	g.GET("/persistent-volume-claims/:name/imports", storage.ListHostDirectoryPVCImports)
	g.POST("/persistent-volume-claims/:name/imports", storage.CreateHostDirectoryPVCImport)
	g.DELETE("/persistent-volume-claims/:name/imports/:id/backup", storage.DeleteHostDirectoryPVCImportBackup)
	g.DELETE("/persistent-volume-claims/:name", storage.DeletePersistentVolumeClaim)
	g.GET("/ingresses", network.ListStandardIngresses)
	g.GET("/ingresses/:namespace/:name", network.GetStandardIngress)
	g.POST("/ingresses", network.CreateStandardIngress)
	g.DELETE("/ingresses/:namespace/:name", network.DeleteStandardIngress)
	g.GET("/ingress-controller", network.StandardIngressController)
}
