// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NginxTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxTestRequest) Reset() {
	*x = NginxTestRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxTestRequest) ProtoMessage() {}

func (x *NginxTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxTestRequest.ProtoReflect.Descriptor instead.
func (*NginxTestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

type NginxTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxTestResponse) Reset() {
	*x = NginxTestResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxTestResponse) ProtoMessage() {}

func (x *NginxTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxTestResponse.ProtoReflect.Descriptor instead.
func (*NginxTestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NginxTestResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NginxTestResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *NginxTestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NginxReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxReloadRequest) Reset() {
	*x = NginxReloadRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxReloadRequest) ProtoMessage() {}

func (x *NginxReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxReloadRequest.ProtoReflect.Descriptor instead.
func (*NginxReloadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

type NginxReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxReloadResponse) Reset() {
	*x = NginxReloadResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxReloadResponse) ProtoMessage() {}

func (x *NginxReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxReloadResponse.ProtoReflect.Descriptor instead.
func (*NginxReloadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NginxReloadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NginxReloadResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *NginxReloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NginxGetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxGetConfigRequest) Reset() {
	*x = NginxGetConfigRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxGetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxGetConfigRequest) ProtoMessage() {}

func (x *NginxGetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxGetConfigRequest.ProtoReflect.Descriptor instead.
func (*NginxGetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

type NginxGetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NginxGetConfigResponse) Reset() {
	*x = NginxGetConfigResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxGetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxGetConfigResponse) ProtoMessage() {}

func (x *NginxGetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxGetConfigResponse.ProtoReflect.Descriptor instead.
func (*NginxGetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NginxGetConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *NginxGetConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteConfigFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigFileRequest) Reset() {
	*x = WriteConfigFileRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigFileRequest) ProtoMessage() {}

func (x *WriteConfigFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigFileRequest.ProtoReflect.Descriptor instead.
func (*WriteConfigFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WriteConfigFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteConfigFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type WriteConfigFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteConfigFileResponse) Reset() {
	*x = WriteConfigFileResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConfigFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConfigFileResponse) ProtoMessage() {}

func (x *WriteConfigFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConfigFileResponse.ProtoReflect.Descriptor instead.
func (*WriteConfigFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *WriteConfigFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WriteConfigFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteConfigFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigFileRequest) Reset() {
	*x = DeleteConfigFileRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigFileRequest) ProtoMessage() {}

func (x *DeleteConfigFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteConfigFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteConfigFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigFileResponse) Reset() {
	*x = DeleteConfigFileResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigFileResponse) ProtoMessage() {}

func (x *DeleteConfigFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteConfigFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteConfigFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatRequest) Reset() {
	*x = FileStatRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatRequest) ProtoMessage() {}

func (x *FileStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatRequest.ProtoReflect.Descriptor instead.
func (*FileStatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *FileStatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          int64                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatResponse) Reset() {
	*x = FileStatResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatResponse) ProtoMessage() {}

func (x *FileStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatResponse.ProtoReflect.Descriptor instead.
func (*FileStatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FileStatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *FileStatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStatResponse) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileStatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcmeIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`                        // http / dns
	Webroot       string                 `protobuf:"bytes,3,opt,name=webroot,proto3" json:"webroot,omitempty"`                            // HTTP challenge 时的 webroot
	DnsProvider   string                 `protobuf:"bytes,4,opt,name=dns_provider,json=dnsProvider,proto3" json:"dns_provider,omitempty"` // DNS challenge 时的 dns 插件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeIssueRequest) Reset() {
	*x = AcmeIssueRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeIssueRequest) ProtoMessage() {}

func (x *AcmeIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeIssueRequest.ProtoReflect.Descriptor instead.
func (*AcmeIssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *AcmeIssueRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AcmeIssueRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *AcmeIssueRequest) GetWebroot() string {
	if x != nil {
		return x.Webroot
	}
	return ""
}

func (x *AcmeIssueRequest) GetDnsProvider() string {
	if x != nil {
		return x.DnsProvider
	}
	return ""
}

type AcmeIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CertPath      string                 `protobuf:"bytes,2,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath       string                 `protobuf:"bytes,3,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	FullchainPath string                 `protobuf:"bytes,4,opt,name=fullchain_path,json=fullchainPath,proto3" json:"fullchain_path,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeIssueResponse) Reset() {
	*x = AcmeIssueResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeIssueResponse) ProtoMessage() {}

func (x *AcmeIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeIssueResponse.ProtoReflect.Descriptor instead.
func (*AcmeIssueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AcmeIssueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcmeIssueResponse) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *AcmeIssueResponse) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *AcmeIssueResponse) GetFullchainPath() string {
	if x != nil {
		return x.FullchainPath
	}
	return ""
}

func (x *AcmeIssueResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *AcmeIssueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcmeRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeRenewRequest) Reset() {
	*x = AcmeRenewRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeRenewRequest) ProtoMessage() {}

func (x *AcmeRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeRenewRequest.ProtoReflect.Descriptor instead.
func (*AcmeRenewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *AcmeRenewRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type AcmeRenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeRenewResponse) Reset() {
	*x = AcmeRenewResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeRenewResponse) ProtoMessage() {}

func (x *AcmeRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeRenewResponse.ProtoReflect.Descriptor instead.
func (*AcmeRenewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *AcmeRenewResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcmeRenewResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *AcmeRenewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcmeRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeRevokeRequest) Reset() {
	*x = AcmeRevokeRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeRevokeRequest) ProtoMessage() {}

func (x *AcmeRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeRevokeRequest.ProtoReflect.Descriptor instead.
func (*AcmeRevokeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *AcmeRevokeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type AcmeRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeRevokeResponse) Reset() {
	*x = AcmeRevokeResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeRevokeResponse) ProtoMessage() {}

func (x *AcmeRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeRevokeResponse.ProtoReflect.Descriptor instead.
func (*AcmeRevokeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *AcmeRevokeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcmeRevokeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *AcmeRevokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcmeDetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeDetectRequest) Reset() {
	*x = AcmeDetectRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeDetectRequest) ProtoMessage() {}

func (x *AcmeDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeDetectRequest.ProtoReflect.Descriptor instead.
func (*AcmeDetectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{22}
}

type AcmeDetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeDetectResponse) Reset() {
	*x = AcmeDetectResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeDetectResponse) ProtoMessage() {}

func (x *AcmeDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeDetectResponse.ProtoReflect.Descriptor instead.
func (*AcmeDetectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *AcmeDetectResponse) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *AcmeDetectResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AcmeDetectResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{24}
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *SystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\x05agent\"\r\n" +
	"\vPingRequest\"8\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x12\n" +
	"\x10NginxTestRequest\"Q\n" +
	"\x11NginxTestResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x14\n" +
	"\x12NginxReloadRequest\"S\n" +
	"\x13NginxReloadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x17\n" +
	"\x15NginxGetConfigRequest\"F\n" +
	"\x16NginxGetConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\x16WriteConfigFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"?\n" +
	"\x17WriteConfigFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x17DeleteConfigFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x18DeleteConfigFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fFileReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"B\n" +
	"\x10FileReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0fFileStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"h\n" +
	"\x10FileStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x03R\x04mode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x85\x01\n" +
	"\x10AcmeIssueRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\x18\n" +
	"\awebroot\x18\x03 \x01(\tR\awebroot\x12!\n" +
	"\fdns_provider\x18\x04 \x01(\tR\vdnsProvider\"\xb0\x01\n" +
	"\x11AcmeIssueResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tcert_path\x18\x02 \x01(\tR\bcertPath\x12\x19\n" +
	"\bkey_path\x18\x03 \x01(\tR\akeyPath\x12%\n" +
	"\x0efullchain_path\x18\x04 \x01(\tR\rfullchainPath\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"*\n" +
	"\x10AcmeRenewRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"Q\n" +
	"\x11AcmeRenewResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"+\n" +
	"\x11AcmeRevokeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"R\n" +
	"\x12AcmeRevokeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x13\n" +
	"\x11AcmeDetectRequest\"`\n" +
	"\x12AcmeDetectResponse\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x13\n" +
	"\x11SystemInfoRequest\"T\n" +
	"\x12SystemInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname2\xfe\x06\n" +
	"\fAgentService\x12/\n" +
	"\x04Ping\x12\x12.agent.PingRequest\x1a\x13.agent.PingResponse\x12>\n" +
	"\tNginxTest\x12\x17.agent.NginxTestRequest\x1a\x18.agent.NginxTestResponse\x12D\n" +
	"\vNginxReload\x12\x19.agent.NginxReloadRequest\x1a\x1a.agent.NginxReloadResponse\x12M\n" +
	"\x0eNginxGetConfig\x12\x1c.agent.NginxGetConfigRequest\x1a\x1d.agent.NginxGetConfigResponse\x12P\n" +
	"\x0fWriteConfigFile\x12\x1d.agent.WriteConfigFileRequest\x1a\x1e.agent.WriteConfigFileResponse\x12S\n" +
	"\x10DeleteConfigFile\x12\x1e.agent.DeleteConfigFileRequest\x1a\x1f.agent.DeleteConfigFileResponse\x12;\n" +
	"\bFileRead\x12\x16.agent.FileReadRequest\x1a\x17.agent.FileReadResponse\x12;\n" +
	"\bFileStat\x12\x16.agent.FileStatRequest\x1a\x17.agent.FileStatResponse\x12>\n" +
	"\tAcmeIssue\x12\x17.agent.AcmeIssueRequest\x1a\x18.agent.AcmeIssueResponse\x12>\n" +
	"\tAcmeRenew\x12\x17.agent.AcmeRenewRequest\x1a\x18.agent.AcmeRenewResponse\x12A\n" +
	"\n" +
	"AcmeRevoke\x12\x18.agent.AcmeRevokeRequest\x1a\x19.agent.AcmeRevokeResponse\x12A\n" +
	"\n" +
	"AcmeDetect\x12\x18.agent.AcmeDetectRequest\x1a\x19.agent.AcmeDetectResponse\x12A\n" +
	"\n" +
	"SystemInfo\x12\x18.agent.SystemInfoRequest\x1a\x19.agent.SystemInfoResponseB2Z0github.com/cylism/cylism-manager/api/proto/agentb\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_proto_agent_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: agent.PingRequest
	(*PingResponse)(nil),             // 1: agent.PingResponse
	(*NginxTestRequest)(nil),         // 2: agent.NginxTestRequest
	(*NginxTestResponse)(nil),        // 3: agent.NginxTestResponse
	(*NginxReloadRequest)(nil),       // 4: agent.NginxReloadRequest
	(*NginxReloadResponse)(nil),      // 5: agent.NginxReloadResponse
	(*NginxGetConfigRequest)(nil),    // 6: agent.NginxGetConfigRequest
	(*NginxGetConfigResponse)(nil),   // 7: agent.NginxGetConfigResponse
	(*WriteConfigFileRequest)(nil),   // 8: agent.WriteConfigFileRequest
	(*WriteConfigFileResponse)(nil),  // 9: agent.WriteConfigFileResponse
	(*DeleteConfigFileRequest)(nil),  // 10: agent.DeleteConfigFileRequest
	(*DeleteConfigFileResponse)(nil), // 11: agent.DeleteConfigFileResponse
	(*FileReadRequest)(nil),          // 12: agent.FileReadRequest
	(*FileReadResponse)(nil),         // 13: agent.FileReadResponse
	(*FileStatRequest)(nil),          // 14: agent.FileStatRequest
	(*FileStatResponse)(nil),         // 15: agent.FileStatResponse
	(*AcmeIssueRequest)(nil),         // 16: agent.AcmeIssueRequest
	(*AcmeIssueResponse)(nil),        // 17: agent.AcmeIssueResponse
	(*AcmeRenewRequest)(nil),         // 18: agent.AcmeRenewRequest
	(*AcmeRenewResponse)(nil),        // 19: agent.AcmeRenewResponse
	(*AcmeRevokeRequest)(nil),        // 20: agent.AcmeRevokeRequest
	(*AcmeRevokeResponse)(nil),       // 21: agent.AcmeRevokeResponse
	(*AcmeDetectRequest)(nil),        // 22: agent.AcmeDetectRequest
	(*AcmeDetectResponse)(nil),       // 23: agent.AcmeDetectResponse
	(*SystemInfoRequest)(nil),        // 24: agent.SystemInfoRequest
	(*SystemInfoResponse)(nil),       // 25: agent.SystemInfoResponse
}
var file_api_proto_agent_proto_depIdxs = []int32{
	0,  // 0: agent.AgentService.Ping:input_type -> agent.PingRequest
	2,  // 1: agent.AgentService.NginxTest:input_type -> agent.NginxTestRequest
	4,  // 2: agent.AgentService.NginxReload:input_type -> agent.NginxReloadRequest
	6,  // 3: agent.AgentService.NginxGetConfig:input_type -> agent.NginxGetConfigRequest
	8,  // 4: agent.AgentService.WriteConfigFile:input_type -> agent.WriteConfigFileRequest
	10, // 5: agent.AgentService.DeleteConfigFile:input_type -> agent.DeleteConfigFileRequest
	12, // 6: agent.AgentService.FileRead:input_type -> agent.FileReadRequest
	14, // 7: agent.AgentService.FileStat:input_type -> agent.FileStatRequest
	16, // 8: agent.AgentService.AcmeIssue:input_type -> agent.AcmeIssueRequest
	18, // 9: agent.AgentService.AcmeRenew:input_type -> agent.AcmeRenewRequest
	20, // 10: agent.AgentService.AcmeRevoke:input_type -> agent.AcmeRevokeRequest
	22, // 11: agent.AgentService.AcmeDetect:input_type -> agent.AcmeDetectRequest
	24, // 12: agent.AgentService.SystemInfo:input_type -> agent.SystemInfoRequest
	1,  // 13: agent.AgentService.Ping:output_type -> agent.PingResponse
	3,  // 14: agent.AgentService.NginxTest:output_type -> agent.NginxTestResponse
	5,  // 15: agent.AgentService.NginxReload:output_type -> agent.NginxReloadResponse
	7,  // 16: agent.AgentService.NginxGetConfig:output_type -> agent.NginxGetConfigResponse
	9,  // 17: agent.AgentService.WriteConfigFile:output_type -> agent.WriteConfigFileResponse
	11, // 18: agent.AgentService.DeleteConfigFile:output_type -> agent.DeleteConfigFileResponse
	13, // 19: agent.AgentService.FileRead:output_type -> agent.FileReadResponse
	15, // 20: agent.AgentService.FileStat:output_type -> agent.FileStatResponse
	17, // 21: agent.AgentService.AcmeIssue:output_type -> agent.AcmeIssueResponse
	19, // 22: agent.AgentService.AcmeRenew:output_type -> agent.AcmeRenewResponse
	21, // 23: agent.AgentService.AcmeRevoke:output_type -> agent.AcmeRevokeResponse
	23, // 24: agent.AgentService.AcmeDetect:output_type -> agent.AcmeDetectResponse
	25, // 25: agent.AgentService.SystemInfo:output_type -> agent.SystemInfoResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
