// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Ping_FullMethodName             = "/agent.AgentService/Ping"
	AgentService_NginxTest_FullMethodName        = "/agent.AgentService/NginxTest"
	AgentService_NginxReload_FullMethodName      = "/agent.AgentService/NginxReload"
	AgentService_NginxGetConfig_FullMethodName   = "/agent.AgentService/NginxGetConfig"
	AgentService_WriteConfigFile_FullMethodName  = "/agent.AgentService/WriteConfigFile"
	AgentService_DeleteConfigFile_FullMethodName = "/agent.AgentService/DeleteConfigFile"
	AgentService_FileRead_FullMethodName         = "/agent.AgentService/FileRead"
	AgentService_FileStat_FullMethodName         = "/agent.AgentService/FileStat"
	AgentService_AcmeIssue_FullMethodName        = "/agent.AgentService/AcmeIssue"
	AgentService_AcmeRenew_FullMethodName        = "/agent.AgentService/AcmeRenew"
	AgentService_AcmeRevoke_FullMethodName       = "/agent.AgentService/AcmeRevoke"
	AgentService_AcmeDetect_FullMethodName       = "/agent.AgentService/AcmeDetect"
	AgentService_SystemInfo_FullMethodName       = "/agent.AgentService/SystemInfo"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService 定义 Agent 暴露给 Platform 的 RPC 接口
type AgentServiceClient interface {
	// 心跳
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// NGINX 操作
	NginxTest(ctx context.Context, in *NginxTestRequest, opts ...grpc.CallOption) (*NginxTestResponse, error)
	NginxReload(ctx context.Context, in *NginxReloadRequest, opts ...grpc.CallOption) (*NginxReloadResponse, error)
	NginxGetConfig(ctx context.Context, in *NginxGetConfigRequest, opts ...grpc.CallOption) (*NginxGetConfigResponse, error)
	// 文件操作
	WriteConfigFile(ctx context.Context, in *WriteConfigFileRequest, opts ...grpc.CallOption) (*WriteConfigFileResponse, error)
	DeleteConfigFile(ctx context.Context, in *DeleteConfigFileRequest, opts ...grpc.CallOption) (*DeleteConfigFileResponse, error)
	FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	FileStat(ctx context.Context, in *FileStatRequest, opts ...grpc.CallOption) (*FileStatResponse, error)
	// acme.sh 操作
	AcmeIssue(ctx context.Context, in *AcmeIssueRequest, opts ...grpc.CallOption) (*AcmeIssueResponse, error)
	AcmeRenew(ctx context.Context, in *AcmeRenewRequest, opts ...grpc.CallOption) (*AcmeRenewResponse, error)
	AcmeRevoke(ctx context.Context, in *AcmeRevokeRequest, opts ...grpc.CallOption) (*AcmeRevokeResponse, error)
	AcmeDetect(ctx context.Context, in *AcmeDetectRequest, opts ...grpc.CallOption) (*AcmeDetectResponse, error)
	// 系统信息
	SystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) NginxTest(ctx context.Context, in *NginxTestRequest, opts ...grpc.CallOption) (*NginxTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NginxTestResponse)
	err := c.cc.Invoke(ctx, AgentService_NginxTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) NginxReload(ctx context.Context, in *NginxReloadRequest, opts ...grpc.CallOption) (*NginxReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NginxReloadResponse)
	err := c.cc.Invoke(ctx, AgentService_NginxReload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) NginxGetConfig(ctx context.Context, in *NginxGetConfigRequest, opts ...grpc.CallOption) (*NginxGetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NginxGetConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_NginxGetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WriteConfigFile(ctx context.Context, in *WriteConfigFileRequest, opts ...grpc.CallOption) (*WriteConfigFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteConfigFileResponse)
	err := c.cc.Invoke(ctx, AgentService_WriteConfigFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteConfigFile(ctx context.Context, in *DeleteConfigFileRequest, opts ...grpc.CallOption) (*DeleteConfigFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigFileResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteConfigFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, AgentService_FileRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileStat(ctx context.Context, in *FileStatRequest, opts ...grpc.CallOption) (*FileStatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileStatResponse)
	err := c.cc.Invoke(ctx, AgentService_FileStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AcmeIssue(ctx context.Context, in *AcmeIssueRequest, opts ...grpc.CallOption) (*AcmeIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcmeIssueResponse)
	err := c.cc.Invoke(ctx, AgentService_AcmeIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AcmeRenew(ctx context.Context, in *AcmeRenewRequest, opts ...grpc.CallOption) (*AcmeRenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcmeRenewResponse)
	err := c.cc.Invoke(ctx, AgentService_AcmeRenew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AcmeRevoke(ctx context.Context, in *AcmeRevokeRequest, opts ...grpc.CallOption) (*AcmeRevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcmeRevokeResponse)
	err := c.cc.Invoke(ctx, AgentService_AcmeRevoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AcmeDetect(ctx context.Context, in *AcmeDetectRequest, opts ...grpc.CallOption) (*AcmeDetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcmeDetectResponse)
	err := c.cc.Invoke(ctx, AgentService_AcmeDetect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_SystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService 定义 Agent 暴露给 Platform 的 RPC 接口
type AgentServiceServer interface {
	// 心跳
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// NGINX 操作
	NginxTest(context.Context, *NginxTestRequest) (*NginxTestResponse, error)
	NginxReload(context.Context, *NginxReloadRequest) (*NginxReloadResponse, error)
	NginxGetConfig(context.Context, *NginxGetConfigRequest) (*NginxGetConfigResponse, error)
	// 文件操作
	WriteConfigFile(context.Context, *WriteConfigFileRequest) (*WriteConfigFileResponse, error)
	DeleteConfigFile(context.Context, *DeleteConfigFileRequest) (*DeleteConfigFileResponse, error)
	FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error)
	FileStat(context.Context, *FileStatRequest) (*FileStatResponse, error)
	// acme.sh 操作
	AcmeIssue(context.Context, *AcmeIssueRequest) (*AcmeIssueResponse, error)
	AcmeRenew(context.Context, *AcmeRenewRequest) (*AcmeRenewResponse, error)
	AcmeRevoke(context.Context, *AcmeRevokeRequest) (*AcmeRevokeResponse, error)
	AcmeDetect(context.Context, *AcmeDetectRequest) (*AcmeDetectResponse, error)
	// 系统信息
	SystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) NginxTest(context.Context, *NginxTestRequest) (*NginxTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NginxTest not implemented")
}
func (UnimplementedAgentServiceServer) NginxReload(context.Context, *NginxReloadRequest) (*NginxReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NginxReload not implemented")
}
func (UnimplementedAgentServiceServer) NginxGetConfig(context.Context, *NginxGetConfigRequest) (*NginxGetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NginxGetConfig not implemented")
}
func (UnimplementedAgentServiceServer) WriteConfigFile(context.Context, *WriteConfigFileRequest) (*WriteConfigFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteConfigFile not implemented")
}
func (UnimplementedAgentServiceServer) DeleteConfigFile(context.Context, *DeleteConfigFileRequest) (*DeleteConfigFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfigFile not implemented")
}
func (UnimplementedAgentServiceServer) FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedAgentServiceServer) FileStat(context.Context, *FileStatRequest) (*FileStatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileStat not implemented")
}
func (UnimplementedAgentServiceServer) AcmeIssue(context.Context, *AcmeIssueRequest) (*AcmeIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcmeIssue not implemented")
}
func (UnimplementedAgentServiceServer) AcmeRenew(context.Context, *AcmeRenewRequest) (*AcmeRenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcmeRenew not implemented")
}
func (UnimplementedAgentServiceServer) AcmeRevoke(context.Context, *AcmeRevokeRequest) (*AcmeRevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcmeRevoke not implemented")
}
func (UnimplementedAgentServiceServer) AcmeDetect(context.Context, *AcmeDetectRequest) (*AcmeDetectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcmeDetect not implemented")
}
func (UnimplementedAgentServiceServer) SystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemInfo not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_NginxTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NginxTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NginxTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_NginxTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NginxTest(ctx, req.(*NginxTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_NginxReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NginxReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NginxReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_NginxReload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NginxReload(ctx, req.(*NginxReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_NginxGetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NginxGetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NginxGetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_NginxGetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NginxGetConfig(ctx, req.(*NginxGetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WriteConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteConfigFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).WriteConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_WriteConfigFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).WriteConfigFile(ctx, req.(*WriteConfigFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteConfigFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteConfigFile(ctx, req.(*DeleteConfigFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileRead(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileStat(ctx, req.(*FileStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AcmeIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AcmeIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AcmeIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AcmeIssue(ctx, req.(*AcmeIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AcmeRenew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeRenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AcmeRenew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AcmeRenew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AcmeRenew(ctx, req.(*AcmeRenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AcmeRevoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeRevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AcmeRevoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AcmeRevoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AcmeRevoke(ctx, req.(*AcmeRevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AcmeDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcmeDetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AcmeDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AcmeDetect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AcmeDetect(ctx, req.(*AcmeDetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
		{
			MethodName: "NginxTest",
			Handler:    _AgentService_NginxTest_Handler,
		},
		{
			MethodName: "NginxReload",
			Handler:    _AgentService_NginxReload_Handler,
		},
		{
			MethodName: "NginxGetConfig",
			Handler:    _AgentService_NginxGetConfig_Handler,
		},
		{
			MethodName: "WriteConfigFile",
			Handler:    _AgentService_WriteConfigFile_Handler,
		},
		{
			MethodName: "DeleteConfigFile",
			Handler:    _AgentService_DeleteConfigFile_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _AgentService_FileRead_Handler,
		},
		{
			MethodName: "FileStat",
			Handler:    _AgentService_FileStat_Handler,
		},
		{
			MethodName: "AcmeIssue",
			Handler:    _AgentService_AcmeIssue_Handler,
		},
		{
			MethodName: "AcmeRenew",
			Handler:    _AgentService_AcmeRenew_Handler,
		},
		{
			MethodName: "AcmeRevoke",
			Handler:    _AgentService_AcmeRevoke_Handler,
		},
		{
			MethodName: "AcmeDetect",
			Handler:    _AgentService_AcmeDetect_Handler,
		},
		{
			MethodName: "SystemInfo",
			Handler:    _AgentService_SystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent.proto",
}
