<template>
  <div>
    <div class="page-header"><div><h1 class="page-title">证书</h1><p class="page-subtitle">管理签发者、受控 DNS Provider 凭据和证书续期</p></div><div v-if="ready" class="btn-group"><button class="btn" @click="openCredential()">DNS 凭据</button><button class="btn" @click="openIssuer()">新增签发者</button><button class="btn btn-primary" @click="showCertificate=true">+ 添加证书</button></div></div>
    <SurfaceCard v-if="loaded&&!ready" class="section-gap"><template #header><div><h2 class="card-title">cert-manager {{ statusTitle }}</h2><p class="status-copy">{{ status?.message }}</p></div></template><template #actions><span class="badge" :class="status?.state==='installing'?'badge-deploying':'badge-danger'">{{ statusTitle }}</span></template><p v-if="error" class="k8s-banner k8s-banner-warn">{{ error }}</p><div class="modal-actions status-actions"><button v-if="status?.state==='not_installed'&&status?.installer_available" class="btn btn-primary" @click="installCertManager">安装 cert-manager</button><button class="btn" @click="refresh">重新检测</button></div></SurfaceCard>
    <template v-if="loaded&&ready">
      <div v-if="error" class="k8s-banner k8s-banner-warn section-gap">{{ error }}</div>
      <section v-if="providers.length" class="provider-grid section-gap"><SurfaceCard v-for="provider in providers" :key="provider.id" as="article" class="provider-card"><template #header><div><h2 class="card-title">{{ provider.name }}</h2><p class="status-copy">{{ provider.description }}</p></div></template><template #actions><span class="badge" :class="provider.status?.ready?'badge-online':provider.status?.state==='installing'?'badge-deploying':'badge-offline'">{{ providerStatusLabel(provider) }}</span></template><div class="provider-actions"><span class="cell-secondary">{{ provider.status?.message }}</span><button v-if="provider.webhook&&provider.status?.state==='not_installed'" class="btn btn-sm" :disabled="installingProvider===provider.id" @click="installProvider(provider.id)">{{ installingProvider===provider.id?'安装中...':'安装 Webhook' }}</button><button v-else class="btn btn-sm" @click="refresh">刷新</button></div></SurfaceCard></section>
      <SurfaceCard v-if="issuers.length" class="section-gap"><template #header><h2 class="card-title">签发者</h2></template><template #actions><span class="section-count">{{ issuers.length }} 项</span></template><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>模式</th><th>Provider</th><th>类型</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="issuer in issuers" :key="issuerKey(issuer)"><td class="cell-primary">{{ issuer.name }}<small class="cell-secondary">{{ issuer.namespace||'集群级' }}</small></td><td>{{ issuerModeLabel(issuer.mode) }}</td><td>{{ providerName(issuer.dns_provider) }}</td><td>{{ issuer.kind }}</td><td><span class="badge" :class="issuer.ready?'badge-online':'badge-danger'">{{ issuer.ready?'就绪':'不可用' }}</span><small v-if="issuer.reason" class="cell-secondary">{{ issuer.reason }}</small></td><td><div class="btn-group action-cell"><button class="btn btn-sm" @click="openIssuer(issuer)">编辑</button><button class="btn btn-sm btn-danger" @click="deleteIssuer(issuer)">删除</button></div></td></tr></tbody></table></div></SurfaceCard>
      <SurfaceCard v-if="credentials.length" class="section-gap"><template #header><h2 class="card-title">DNS 凭据</h2></template><template #actions><span class="section-count">{{ credentials.length }} 项</span></template><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>Provider</th><th>命名空间</th><th>已配置字段</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="credential in credentials" :key="credential.id"><td class="cell-primary">{{ credential.name }}</td><td>{{ providerName(credential.provider) }}</td><td>{{ credential.namespace }}</td><td>{{ configuredFieldLabels(credential).join('、')||'-' }}</td><td><span class="badge" :class="credential.enabled?'badge-online':'badge-offline'">{{ credential.enabled?'启用':'停用' }}</span></td><td><div class="btn-group action-cell"><button class="btn btn-sm" @click="openCredential(credential)">编辑</button><button class="btn btn-sm btn-danger" @click="deleteCredential(credential)">删除</button></div></td></tr></tbody></table></div></SurfaceCard>
      <SurfaceCard v-if="certs.length" class="section-gap"><template #header><h2 class="card-title">证书</h2></template><template #actions><span class="section-count">{{ certs.length }} 项</span></template><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>命名空间</th><th>域名</th><th>签发者</th><th>TLS Secret</th><th>续期时间</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="cert in certs" :key="cert.namespace+'/'+cert.name"><td class="cell-primary">{{ cert.name }}</td><td>{{ cert.namespace }}</td><td>{{ cert.domains?.join(', ') }}</td><td>{{ cert.issuer }}<small class="cell-secondary">{{ cert.issuer_kind }}</small></td><td>{{ cert.secret_name||'-' }}</td><td>{{ formatDate(cert.renewal_time) }}</td><td><span class="badge" :class="cert.status==='Ready'?'badge-online':cert.status==='Failed'?'badge-danger':'badge-deploying'">{{ cert.status==='Ready'?'就绪':cert.status==='Failed'?'失败':'签发中' }}</span></td><td><div class="btn-group action-cell"><button class="btn btn-sm" @click="router.push(`/network/certificates/${cert.namespace}/${cert.name}`)">签发过程</button><button class="btn btn-sm btn-danger" @click="deleteCertificate(cert)">删除</button></div></td></tr></tbody></table></div></SurfaceCard>
      <div v-if="!certs.length&&!issuers.length&&!credentials.length" class="empty-state certificate-empty"><FileCheck2 data-testid="certificate-empty-icon" :size="30" :stroke-width="1.5" /><span class="empty-text">尚未发现证书、签发者或 DNS 凭据</span></div>
    </template>
    <div v-if="showCertificate" class="overlay" @click.self="showCertificate=false"><div class="modal"><h2 class="modal-title">添加证书</h2><form @submit.prevent="createCertificate"><div class="form-row"><div class="form-group"><label class="form-label">名称</label><input v-model.trim="certificateForm.name" class="form-input" placeholder="my-cert" required /></div><div class="form-group"><label class="form-label">命名空间</label><input v-model.trim="certificateForm.namespace" class="form-input" placeholder="default" required /></div></div><div class="form-group"><label class="form-label">域名</label><input v-model="certificateForm.domains" class="form-input" placeholder="example.com,*.example.com" required /></div><div class="form-group"><label class="form-label">签发者</label><SelectMenu v-model="certificateForm.issuer" class="form-select" required><option value="" disabled>选择可用签发者</option><option v-for="issuer in availableIssuers" :key="issuerKey(issuer)" :value="issuerKey(issuer)">{{ issuer.kind }} · {{ issuer.name }}</option></SelectMenu></div><div class="modal-actions"><button type="button" class="btn" @click="showCertificate=false">取消</button><button class="btn btn-primary" :disabled="submitting||!availableIssuers.length">创建证书</button></div></form></div></div>
    <div v-if="showIssuer" class="overlay" @click.self="showIssuer=false"><div class="modal"><h2 class="modal-title">{{ editingIssuer?'编辑签发者':'新增签发者' }}</h2><form @submit.prevent="saveIssuer"><div class="form-row"><div class="form-group"><label class="form-label">名称</label><input v-model.trim="issuerForm.name" class="form-input" required :disabled="!!editingIssuer" /></div><div class="form-group"><label class="form-label">类型</label><SelectMenu v-model="issuerForm.kind" class="form-select" :disabled="!!editingIssuer"><option value="ClusterIssuer">ClusterIssuer</option><option value="Issuer">Issuer</option></SelectMenu></div></div><div v-if="issuerForm.kind==='Issuer'" class="form-group"><label class="form-label">命名空间</label><input v-model.trim="issuerForm.namespace" class="form-input" required :disabled="!!editingIssuer" /></div><div class="form-group"><label class="form-label">签发模式</label><SelectMenu v-model="issuerForm.mode" class="form-select"><option value="acme_http01">ACME HTTP-01</option><option value="acme_dns01">DNS-01</option><option value="self_signed">自签名</option></SelectMenu></div><template v-if="issuerForm.mode!=='self_signed'"><div class="form-group"><label class="form-label">ACME 邮箱</label><input v-model.trim="issuerForm.email" type="email" class="form-input" required /></div><div v-if="issuerForm.mode==='acme_http01'" class="form-group"><label class="form-label">Ingress Class</label><input v-model.trim="issuerForm.ingress_class" class="form-input" placeholder="traefik" /></div><template v-else><div class="form-group"><label class="form-label">DNS Provider</label><SelectMenu v-model="issuerForm.dns_provider" class="form-select"><option value="" disabled>选择已就绪 Provider</option><option v-for="provider in readyProviders" :key="provider.id" :value="provider.id">{{ provider.name }}</option></SelectMenu></div><div class="form-group"><label class="form-label">DNS 凭据</label><SelectMenu v-model.number="issuerForm.credential_id" class="form-select" required><option :value="0" disabled>选择凭据</option><option v-for="credential in eligibleCredentials" :key="credential.id" :value="credential.id">{{ credential.name }} · {{ credential.namespace }}</option></SelectMenu></div></template></template><div class="modal-actions"><button type="button" class="btn" @click="showIssuer=false">取消</button><button class="btn btn-primary" :disabled="submitting">保存</button></div></form></div></div>
    <div v-if="showCredential" class="overlay" @click.self="showCredential=false"><div class="modal"><h2 class="modal-title">{{ editingCredential?'编辑 DNS 凭据':'新增 DNS 凭据' }}</h2><form @submit.prevent="saveCredential"><div class="form-row"><div class="form-group"><label class="form-label">名称</label><input v-model.trim="credentialForm.name" class="form-input" required /></div><div class="form-group"><label class="form-label">Provider</label><SelectMenu v-model="credentialForm.provider" class="form-select" :disabled="!!editingCredential"><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{ provider.name }}</option></SelectMenu></div></div><div class="form-group"><label class="form-label">命名空间</label><input v-model.trim="credentialForm.namespace" class="form-input" required /></div><div v-for="field in credentialFields" :key="field.key" class="form-group"><label class="form-label">{{ field.label }}</label><input v-model="credentialForm.values[field.key]" class="form-input" :type="field.secret?'password':'text'" :placeholder="editingCredential&&field.secret?'留空则保留现有值':''" /></div><label class="check-row"><input v-model="credentialForm.enabled" type="checkbox" /> 启用此凭据</label><div class="modal-actions"><button type="button" class="btn" @click="showCredential=false">取消</button><button class="btn btn-primary" :disabled="submitting">保存</button></div></form></div></div>
  </div>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { FileCheck2 } from 'lucide-vue-next'
import SurfaceCard from '../../components/SurfaceCard.vue'
import { createCertificate as createCertificateRequest, createDNSCredential, createIssuer, deleteCertificate as removeCertificate, deleteDNSCredential, deleteIssuer as removeIssuer, installCertificateManager, installDNSProvider, getCertificateResources, getCertificateStatus, updateDNSCredential, updateIssuer } from '../../api/certificates.js'
import { useAsyncResource } from '../../composables/useAsyncResource.js'
const router=useRouter(), certs=ref([]), issuers=ref([]), credentials=ref([]), providers=ref([]), status=ref(null), loaded=ref(false), statusError=ref(''), resourceError=ref(''), mutationError=ref(''), submitting=ref(false), installingProvider=ref('')
const error = computed(() => mutationError.value || resourceError.value || statusError.value)
const showCertificate=ref(false),showIssuer=ref(false),showCredential=ref(false),editingIssuer=ref(null),editingCredential=ref(null)
const certificateForm=ref(newCertificate()),issuerForm=ref(newIssuer()),credentialForm=ref(newCredential())
const createQueryHandled = ref(false)
const ready=computed(()=>status.value?.state==='ready'), statusTitle=computed(()=>({ready:'已就绪',not_installed:'未安装',installing:'安装中',degraded:'异常',unauthorized:'未授权',unavailable:'不可用'}[status.value?.state]||'状态未知'))
const availableIssuers=computed(()=>issuers.value.filter(i=>i.ready&&(i.kind==='ClusterIssuer'||i.namespace===certificateForm.value.namespace)))
const readyProviders=computed(()=>providers.value.filter(p=>p.status?.ready)), credentialFields=computed(()=>providers.value.find(p=>p.id===credentialForm.value.provider)?.fields||[])
const eligibleCredentials=computed(()=>credentials.value.filter(c=>c.enabled&&c.provider===issuerForm.value.dns_provider&&(issuerForm.value.kind==='ClusterIssuer'||c.namespace===issuerForm.value.namespace)))
const certificateResource = useAsyncResource(async ({ signal }) => {
  const currentStatus = await getCertificateStatus({ signal })
  if (currentStatus?.state !== 'ready') return { status: currentStatus, resources: null }
  return { status: currentStatus, resources: await getCertificateResources({ signal }) }
}, null)
onMounted(refresh);watch(()=>certificateForm.value.namespace,()=>{if(!availableIssuers.value.some(i=>issuerKey(i)===certificateForm.value.issuer))certificateForm.value.issuer=availableIssuers.value[0]?issuerKey(availableIssuers.value[0]):''});watch(()=>issuerForm.value.dns_provider,()=>issuerForm.value.credential_id=0)
async function refresh(){statusError.value='';resourceError.value='';mutationError.value='';const result=await certificateResource.refresh();if(result){status.value=result.status;if(result.resources){const [a,b,c,d]=result.resources;certs.value=a||[];issuers.value=b||[];credentials.value=c||[];providers.value=d||[];applyCreateQuery()}}else if(certificateResource.error.value)resourceError.value=certificateResource.error.value.message||'加载证书管理资源失败';loaded.value=true}
async function installCertManager(){mutationError.value='';try{await installCertificateManager();await refresh()}catch(e){mutationError.value=e.message||'安装失败'}}
async function installProvider(id){installingProvider.value=id;mutationError.value='';try{await installDNSProvider(id);await refresh()}catch(e){mutationError.value=e.message||'安装 Provider 失败'}finally{installingProvider.value=''}}
async function createCertificate(){const issuer=availableIssuers.value.find(i=>issuerKey(i)===certificateForm.value.issuer);if(!issuer)return;submitting.value=true;mutationError.value='';try{await createCertificateRequest({name:certificateForm.value.name,namespace:certificateForm.value.namespace,domains:certificateForm.value.domains.split(',').map(x=>x.trim()).filter(Boolean),issuer_ref:issuer.name,issuer_kind:issuer.kind});showCertificate.value=false;await refresh()}catch(e){mutationError.value=e.message||'创建证书失败'}finally{submitting.value=false}}
function openIssuer(item=null){editingIssuer.value=item;issuerForm.value=item?{name:item.name,namespace:item.namespace||'',kind:item.kind,mode:item.mode||'acme_http01',email:item.email||'',ingress_class:'traefik',dns_provider:item.dns_provider||'',credential_id:0}:newIssuer();showIssuer.value=true}
async function saveIssuer(){submitting.value=true;mutationError.value='';try{if(editingIssuer.value)await updateIssuer(issuerForm.value.kind,issuerForm.value.namespace,issuerForm.value.name,issuerForm.value);else await createIssuer(issuerForm.value);showIssuer.value=false;await refresh()}catch(e){mutationError.value=e.message||'保存签发者失败'}finally{submitting.value=false}}
async function deleteIssuer(item){if(!window.confirm(`删除签发者 ${item.name}？`))return;mutationError.value='';try{await removeIssuer(item.kind,item.namespace,item.name);await refresh()}catch(e){mutationError.value=e.message||'删除签发者失败'}}
function openCredential(item=null){editingCredential.value=item;credentialForm.value=item?{name:item.name,provider:item.provider,namespace:item.namespace,values:{},enabled:item.enabled}:newCredential();showCredential.value=true}
async function saveCredential(){submitting.value=true;mutationError.value='';try{const values={...credentialForm.value.values};Object.keys(values).forEach(k=>{if(!values[k])delete values[k]});const body={...credentialForm.value,values};if(editingCredential.value)await updateDNSCredential(editingCredential.value.id,body);else await createDNSCredential(body);showCredential.value=false;await refresh()}catch(e){mutationError.value=e.message||'保存 DNS 凭据失败'}finally{submitting.value=false}}
async function deleteCredential(item){if(!window.confirm(`删除 DNS 凭据 ${item.name}？`))return;mutationError.value='';try{await deleteDNSCredential(item.id);await refresh()}catch(e){mutationError.value=e.message||'删除 DNS 凭据失败'}}
async function deleteCertificate(cert){if(!window.confirm(`删除证书 ${cert.name}？`))return;mutationError.value='';try{await removeCertificate(cert.namespace,cert.name);await refresh()}catch(e){mutationError.value=e.message||'删除证书失败'}}
function applyCreateQuery(){if(createQueryHandled.value||typeof window==='undefined'||!ready.value)return;const query=new URLSearchParams(window.location.hash.split('?')[1]||'');if(query.get('create')!=='1')return;createQueryHandled.value=true;certificateForm.value={...newCertificate(),name:query.get('name')||'',namespace:query.get('namespace')||'cylism-system',domains:query.get('domains')||''};showCertificate.value=true}
function issuerKey(i){return `${i.kind}/${i.namespace||'_'}/${i.name}`}function providerName(id){return providers.value.find(p=>p.id===id)?.name||id||'-'}function providerStatusLabel(p){return p.status?.ready?'已就绪':({not_installed:'未安装',installing:'安装中'}[p.status?.state]||'不可用')}function issuerModeLabel(v){return({self_signed:'自签名',acme_http01:'ACME HTTP-01',acme_dns01:'DNS-01'}[v]||'-')}function configuredFieldLabels(c){const p=providers.value.find(x=>x.id===c.provider);return(p?.fields||[]).filter(f=>(c.configured_fields||[]).includes(f.key)).map(f=>f.label)}function formatDate(v){return v?new Date(v).toLocaleString('zh-CN'):'-'}function newCertificate(){return{name:'',namespace:'default',domains:'',issuer:''}}function newIssuer(){return{name:'',namespace:'',kind:'ClusterIssuer',mode:'acme_http01',email:'',ingress_class:'traefik',dns_provider:'',credential_id:0}}function newCredential(){return{name:'',provider:providers.value[0]?.id||'alidns',namespace:'cert-manager',values:{},enabled:true}}
</script>
<style scoped>.page-header{display:flex;justify-content:space-between;gap:var(--space-16)}.status-copy,.cell-secondary{margin:4px 0 0;color:var(--text-secondary);font-size:11px}.status-actions{justify-content:flex-start;margin-top:16px}.provider-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:var(--space-12)}.provider-card{margin:0}.provider-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:16px}.check-row{display:flex;gap:8px;align-items:center;color:var(--text-secondary);font-size:13px}.certificate-empty{min-height:150px}@media(max-width:640px){.page-header{flex-direction:column}.page-header .btn-group{display:grid;grid-template-columns:1fr 1fr}.page-header .btn-primary{grid-column:span 2}.provider-actions{align-items:flex-start;flex-direction:column}}</style>
