<template>
  <Teleport to="body">
    <section v-if="open" class="assistant-panel" aria-label="Cylism 智能助手">
      <header><div><strong>智能助手</strong><small>{{ configured ? "只读诊断" : "尚未配置模型" }}</small></div><div><button class="icon-button" type="button" aria-label="隐藏助手" @click="hide"><EyeOff :size="16" /></button><button class="icon-button" type="button" aria-label="关闭助手" @click="open = false"><X :size="16" /></button></div></header>
      <div ref="messageList" class="assistant-messages"><div v-if="!messages.length" class="assistant-empty"><Sparkles :size="20" /><p>告诉我你想排查的运行问题。</p></div><article v-for="message in messages" :key="message.key" :class="{ 'assistant-message': true, 'is-user': message.role === 'user' }"><span>{{ message.role === "user" ? "你" : "助手" }}</span><p>{{ message.content }}</p></article><div v-if="sending" class="assistant-message"><span>助手</span><p>正在查询受限的集群数据...</p></div></div>
      <form @submit.prevent="send"><textarea v-model.trim="question" rows="2" maxlength="4000" :disabled="sending || !configured" placeholder="例如：为什么 Karakeep 抓取失败？" /><button class="icon-button" type="submit" aria-label="发送问题" :disabled="sending || !question || !configured"><Send :size="17" /></button></form>
      <p v-if="error" class="assistant-error">{{ error }}</p>
    </section>
    <button v-if="!hidden" class="assistant-trigger" type="button" aria-label="打开智能助手" @click="open = !open"><Bot :size="20" /></button>
  </Teleport>
</template>
<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue"
import { useRoute } from "vue-router"
import { Bot, EyeOff, Send, Sparkles, X } from "lucide-vue-next"
import { api } from "../api/index.js"
const route = useRoute(); const hidden = ref(localStorage.getItem("cylism-assistant-hidden") === "true"); const open = ref(false); const configured = ref(false); const sending = ref(false); const error = ref(""); const conversationID = ref(null); const question = ref(""); const messages = ref([]); const messageList = ref(null)
async function refreshStatus() { try { configured.value = (await api.get("/assistant/status")).configured } catch { configured.value = false } }
function pageContext() { return { route: route.fullPath, page: route.name || route.path } }
function hide() { hidden.value = true; open.value = false; localStorage.setItem("cylism-assistant-hidden", "true") }
function shortcut(event) { if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === "k") { event.preventDefault(); hidden.value = false; localStorage.removeItem("cylism-assistant-hidden"); open.value = !open.value } }
async function send() { if (!question.value || sending.value || !configured.value) return; const content = question.value; question.value = ""; messages.value.push({ key: `u-${Date.now()}`, role: "user", content }); sending.value = true; error.value = ""; try { if (!conversationID.value) conversationID.value = (await api.post("/assistant/conversations", {})).id; const result = await api.post(`/assistant/conversations/${conversationID.value}/messages`, { message: content, page_context: pageContext() }); messages.value.push({ key: `a-${result.message.id}`, role: "assistant", content: result.message.content }) } catch (cause) { error.value = cause.message || "助手暂时无法响应" } finally { sending.value = false } }
watch(messages, async () => { await nextTick(); messageList.value?.scrollTo({ top: messageList.value.scrollHeight, behavior: "smooth" }) }, { deep: true }); onMounted(() => { refreshStatus(); window.addEventListener("keydown", shortcut) }); onBeforeUnmount(() => window.removeEventListener("keydown", shortcut))
</script>
<style scoped>
.assistant-trigger{position:fixed;z-index:1200;right:24px;bottom:24px;display:grid;width:46px;height:46px;place-items:center;border:1px solid var(--border);border-radius:50%;background:var(--surface-raised);color:var(--action-primary);box-shadow:var(--shadow);cursor:pointer}.assistant-panel{position:fixed;z-index:1200;right:24px;bottom:82px;display:grid;width:min(390px,calc(100vw - 32px));height:min(560px,calc(100dvh - 112px));grid-template-rows:auto 1fr auto auto;overflow:hidden;border:1px solid var(--border);border-radius:var(--radius-panel);background:var(--surface-raised);box-shadow:var(--shadow)}header{display:flex;justify-content:space-between;padding:16px;border-bottom:1px solid var(--border-muted)}header strong,header small{display:block}header small{margin-top:3px;color:var(--text-secondary);font-size:11px}.assistant-messages{display:grid;align-content:start;gap:12px;overflow:auto;padding:16px}.assistant-empty{display:grid;justify-items:start;gap:8px;color:var(--text-secondary)}.assistant-empty p,.assistant-message p{margin:0;font-size:12px;line-height:1.55}.assistant-message{display:grid;gap:4px;max-width:92%;padding:10px;border:1px solid var(--border-muted);border-radius:var(--radius-control);background:var(--surface-subtle)}.assistant-message.is-user{justify-self:end;background:var(--surface-hover)}.assistant-message span{color:var(--text-secondary);font-size:10px;font-weight:700}.assistant-panel form{display:grid;grid-template-columns:1fr auto;gap:8px;padding:12px 16px;border-top:1px solid var(--border-muted)}textarea{width:100%;resize:none;border:1px solid var(--border-muted);border-radius:var(--radius-control);background:var(--surface-subtle);color:var(--text-primary);font:12px/1.45 var(--font-body);padding:8px}.assistant-error{margin:0;padding:0 16px 12px;color:var(--danger);font-size:11px}@media(max-width:640px){.assistant-trigger{right:16px;bottom:16px}.assistant-panel{right:16px;bottom:72px}}
</style>
