<template>
  <section class="card assistant-settings">
    <div class="card-header"><div><h2 class="card-title">智能助手</h2><p class="settings-copy">平台管理 PydanticAI Runtime、模型密钥和专用审计存储。</p></div><span class="badge" :class="{ 'badge-online': status.configured, 'badge-offline': !status.configured }">{{ status.configured ? "模型已配置" : "待配置" }}</span></div>
    <div class="assistant-settings-grid"><form class="assistant-provider" @submit.prevent="saveProvider"><h3>模型提供商</h3><label class="form-group"><span class="form-label">名称</span><input v-model.trim="provider.name" class="form-input" required placeholder="OpenAI" /></label><label class="form-group"><span class="form-label">模型</span><input v-model.trim="provider.model" class="form-input" required placeholder="gpt-4o-mini" /></label><label class="form-group"><span class="form-label">Base URL</span><input v-model.trim="provider.base_url" class="form-input" placeholder="OpenAI-compatible 地址可选" /></label><label class="form-group"><span class="form-label">API Key</span><input v-model.trim="provider.api_key" class="form-input" type="password" required placeholder="仅保存密文" /></label><button class="btn btn-primary" :disabled="savingProvider">{{ savingProvider ? "保存中..." : "保存并设为默认" }}</button></form><form class="assistant-install" @submit.prevent="install"><h3>Runtime 部署</h3><label class="form-group"><span class="form-label">模型提供商</span><select v-model.number="installForm.provider_id" class="form-select" required><option :value="0" disabled>选择已保存的模型</option><option v-for="item in providers" :key="item.id" :value="item.id">{{ item.name }} · {{ item.model }}</option></select></label><label class="form-group"><span class="form-label">目标节点</span><select v-model="installForm.node_name" class="form-select" required><option value="" disabled>选择就绪节点</option><option v-for="node in readyNodes" :key="node.name" :value="node.name">{{ node.display_name || node.name }}</option></select></label><label class="form-group"><span class="form-label">审计 PVC 容量</span><input v-model.trim="installForm.storage" class="form-input" required placeholder="1Gi" /></label><button class="btn btn-primary" :disabled="installing || !providers.length">{{ installing ? "部署中..." : "部署或更新 Runtime" }}</button></form></div>
    <p v-if="message" class="settings-copy assistant-result">{{ message }}</p>
  </section>
</template>
<script setup>
import { computed, onMounted, ref } from "vue"
import { api } from "../api/index.js"
const status = ref({ configured: false }); const providers = ref([]); const nodes = ref([]); const message = ref(""); const savingProvider = ref(false); const installing = ref(false); const provider = ref({ name: "", provider_type: "openai_compatible", base_url: "", model: "", api_key: "", enabled: true, is_default: true }); const installForm = ref({ provider_id: 0, node_name: "", storage: "1Gi" }); const readyNodes = computed(() => nodes.value.filter(node => node.ready !== false))
async function refresh() { const [nextStatus, providerResult, nodeResult] = await Promise.allSettled([api.get("/assistant/status"), api.get("/assistant/providers"), api.get("/nodes")]); if (nextStatus.status === "fulfilled") status.value = nextStatus.value; if (providerResult.status === "fulfilled") { providers.value = providerResult.value.providers || []; installForm.value.provider_id = Number(providerResult.value.default_provider_id) || providers.value[0]?.id || 0 } if (nodeResult.status === "fulfilled") nodes.value = nodeResult.value || [] }
async function saveProvider() { savingProvider.value = true; message.value = ""; try { await api.post("/assistant/providers", provider.value); provider.value.api_key = ""; message.value = "模型提供商已保存"; await refresh() } catch (error) { message.value = error.message || "保存失败" } finally { savingProvider.value = false } }
async function install() { installing.value = true; message.value = ""; try { const result = await api.post("/assistant/install", installForm.value); message.value = result.message || "Runtime 已提交部署"; await refresh() } catch (error) { message.value = error.message || "部署失败" } finally { installing.value = false } }
onMounted(refresh)
</script>
<style scoped>
.assistant-settings{grid-column:1/-1}.assistant-settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-20);margin-top:var(--space-16)}.assistant-settings-grid form{display:grid;align-content:start;gap:10px;padding:14px;border:1px solid var(--border-muted);border-radius:var(--radius-control);background:var(--surface-subtle)}h3{margin:0 0 2px;font-size:14px}.assistant-result{margin-top:var(--space-16)}@media(max-width:700px){.assistant-settings-grid{grid-template-columns:1fr}}
</style>
